# Generated by Django 5.1.6 on 2025-03-30 03:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ma_sv', models.IntegerField(unique=True)),
                ('mat_khau', models.CharField(blank=True, max_length=255, null=True)),
                ('ho_ten', models.CharField(max_length=255)),
                ('id_rfid', models.CharField(max_length=255, unique=True)),
                ('so_tien_hien_co', models.FloatField(default=0)),
                ('trang_thai', models.CharField(default='Chưa đỗ', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LichSuNapTien',
            fields=[
                ('ma_nap_tien', models.BigAutoField(primary_key=True, serialize=False)),
                ('so_tien', models.FloatField()),
                ('thoi_gian_nap', models.DateTimeField(auto_now_add=True)),
                ('phuong_thuc', models.CharField(max_length=255)),
                ('ma_giao_dich', models.CharField(max_length=255, unique=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LichSuRaVao',
            fields=[
                ('ma_lich_su', models.BigAutoField(primary_key=True, serialize=False)),
                ('bien_so_xe', models.CharField(max_length=50)),
                ('thoi_gian_vao', models.DateTimeField()),
                ('thoi_gian_ra', models.DateTimeField(blank=True, null=True)),
                ('trang_thai', models.CharField(max_length=50)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LichSuThanhToan',
            fields=[
                ('ma_thanh_toan', models.BigAutoField(primary_key=True, serialize=False)),
                ('so_tien', models.FloatField()),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
