# Generated by Django 5.1.6 on 2025-03-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinhvien',
            name='trang_thai',
            field=models.CharField(default='Chưa đỗ', max_length=50),
        ),
    ]
