# Generated by Django 5.1.6 on 2025-04-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuanTriVien',
            fields=[
                ('ma_qtv', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ho_ten', models.CharField(max_length=255)),
                ('mat_khau', models.CharField(max_length=255)),
                ('vai_tro', models.CharField(max_length=100)),
            ],
        ),
    ]
