# Generated by Django 5.1.6 on 2025-03-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quan_tri_vien', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantrivien',
            name='so_dien_thoai',
        ),
    ]
